#!/bin/zsh
alias sudo="sudo "
# ls
case $(uname -s) in
	Darwin | FreeBSD)
		alias ls="ls -Ghp"
		alias ll="ls -lAtr -D %Y-%m-%dT%H:%M:%S"
		;;
	Linux)
		alias ls="ls --color -hp"
		alias ll="ls -lAtr --time-style=+%Y-%m-%dT%H:%M:%S"
		;;
esac
alias gp="grep -E -inH --color=auto"
alias df="df -ha"
alias cp="cp -v"
alias mv="mv -v"
alias tmuxl="tmux ls"
alias tmuxa="tmux attach -t"
alias tmuxk="tmux kill-session -t"
alias tmuxs="tmux new-session -s"
alias hg='history 0 | awk '\''{for (i=2; i<NF; i++) printf "%s ", $i; print $NF}'\'' | grep -E --color=auto'
alias ifconfig-l="ifconfig -l | sed 's/ /\n/g'"

function ff { ll $1 | awk -v name="$2" 'tolower($NF) ~ name {print}' }
function ffind { find $1 -type f -exec grep -F -inH --color=auto $2 {} + 2> /dev/null }
function efind { find $1 -type f -exec grep -E -inH --color=auto $2 {} + 2> /dev/null }

function tping { ping "$@" | while read pong; do echo "$(date +'%T'): $pong"; done }
function tping6 { ping6 "$@" | while read pong; do echo "$(date +'%T'): $pong"; done }

alias bsp="birdc show protocol"
alias bsp6="birdc6 show protocol"
alias bsr="birdc show route"
alias bsr6="birdc6 show route"

alias ctree="tree --filesfirst -I __pycache__"

mdig () {
	digall_color_restore='\033[0m'
	digall_color_light_green='\033[1;32m'
	digall_color_light_blue='\033[1;34m'
	digall_color_light_cyan='\033[1;36m'
	# Don't use ANY
	for t in A AAAA NS; do
		cmd="dig -t $t +noall +answer "$@""
		echo "${digall_color_light_green}$t:${digall_color_restore}${digall_color_light_cyan}"
		eval "$cmd"
		echo "${digall_color_restore}"
	done
}

gosandbox() {
	local name=${1:-"$(date -u +%Y%m%d_%H%M%S)"}
	local dir="${HOME}/tmp/gosandbox/${name}"
	local templates_dir="${XDG_CONFIG_HOME:-$HOME/.config}/gosandbox"
	mkdir -p "$dir"

	tar -cf - -C "$templates_dir" . | tar -xf - -C "$dir"

	pushd "$dir" > /dev/null
	go mod init "ttl256.me/ttl256/sandbox" &> /dev/null || { echo "go mod init" && return 1; }
	popd > /dev/null

	echo "Go sandbox created at $dir"
	echo "Opening in VS Code..."

	code "$dir" "$dir/main.go"
}

alias cfg='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

[ "$EDITOR" = "nvim" ] && alias vim="nvim"
