#!/bin/zsh
alias sudo="sudo "
# ls
case $(uname -s) in
	Darwin | FreeBSD)
		alias ls="ls -Ghp"
		alias ll="ls -lAtr -D %Y-%m-%dT%H:%M:%S"
		;;
	Linux)
		alias ls="ls --color -hp"
		alias ll="ls -lAtr --time-style=+%Y-%m-%dT%H:%M:%S"
		;;
esac
alias gp="grep -E -inH --color=auto"
alias df="df -ha"
alias cp="cp -v"
alias mv="mv -v"
alias tmuxl="tmux ls"
alias tmuxa="tmux attach -t"
alias tmuxk="tmux kill-session -t"
alias tmuxs="tmux new-session -s"
alias hg='history 0 | awk '\''{for (i=2; i<NF; i++) printf "%s ", $i; print $NF}'\'' | grep -E --color=auto'
alias ifconfig-l="ifconfig -l | sed 's/ /\n/g'"

function ff { ll $1 | awk -v name="$2" 'tolower($NF) ~ name {print}' }
function ffind { find $1 -type f -exec grep -F -inH --color=auto $2 {} + 2> /dev/null }
function efind { find $1 -type f -exec grep -E -inH --color=auto $2 {} + 2> /dev/null }

function tping { ping "$@" | while read pong; do echo "$(date +'%T'): $pong"; done }
function tping6 { ping6 "$@" | while read pong; do echo "$(date +'%T'): $pong"; done }

alias bsp="birdc show protocol"
alias bsp6="birdc6 show protocol"
alias bsr="birdc show route"
alias bsr6="birdc6 show route"

alias ctree="tree --filesfirst -I __pycache__"

function ifconfig {
PYTHON_ARG="$@" python3 - <<END
import os
import re
import subprocess
def mask_hex_to_length(h):
	return bin(int(h, 16)).count("1")
args = os.environ["PYTHON_ARG"]
cmd = f"/sbin/ifconfig {args}"
output = subprocess.run(cmd.split(), stdout=subprocess.PIPE, encoding="utf-8")
if output.stdout:
	regex = re.compile(r"(netmask) (0x[0-9a-f]{8})")
	print(regex.sub(lambda m: f"{m.group(1)} {mask_hex_to_length(m.group(2))}", output.stdout), end="")
END
}

mdig () {
	digall_color_restore='\033[0m'
	digall_color_light_green='\033[1;32m'
	digall_color_light_blue='\033[1;34m'
	digall_color_light_cyan='\033[1;36m'
	# Don't use ANY
	for t in A AAAA NS; do
		cmd="dig -t $t +noall +answer "$@""
		echo "${digall_color_light_green}$t:${digall_color_restore}${digall_color_light_cyan}"
		eval "$cmd"
		echo "${digall_color_restore}"
	done
}

gosandbox() {
    name=${1:-"go-sandbox-$(date +%Y%m%d-%H%M%S)"}
    dir="${HOME}/tmp/gosandbox/${name}"
    mkdir -p "$dir"

    echo "//nolint:forbidigo //let me be
package main

import \"fmt\"

func main() {
\tfmt.Println(\"Hello, Go Sandbox!\")
}

func Dummy() {}
" > "$dir/main.go"

    echo "package main_test

import (
\t\"testing\"
\tsb \"ttl256.me/ttl256/sandbox\"
)

func TestDummy(t *testing.T) {
\tsb.Dummy() // TODO: Add your tests here
}
" > "$dir/main_test.go"

    echo "# Makefile for Go sandbox

.PHONY: run build test clean

run:
\tgo run main.go

build:
\tgo build -o app main.go

test:
\tgo test -v ./...

bench:
\tgo test -bench=. ./...

cover:
\tgo test -cover ./...

clean:
\trm -f app
" > "$dir/Makefile"

    modname="ttl256.me/ttl256/sandbox"

    pushd "$dir" > /dev/null && go mod init "$modname" > /dev/null 2>&1 && popd > /dev/null

    echo "Go sandbox created at $dir"
    echo "Opening in VS Code..."

    code "$dir" "$dir/main.go"
}

alias cfg='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

[ "$EDITOR" = "nvim" ] && alias vim="nvim"
